// languages.js
// const languages = [
//     { name: 'C', mode: 'text/x-csrc' },
//     { name: 'Clojure', mode: 'text/x-clojure' },
//     { name: 'COBOL', mode: 'text/x-cobol' },
//     { name: 'CoffeeScript', mode: 'text/coffeescript' },
//     { name: 'C++', mode: 'text/x-c++src' },
//     { name: 'C#', mode: 'text/x-csharp' },
//     { name: 'D', mode: 'text/x-d' },
//     { name: 'Dart', mode: 'application/dart' },
//     { name: 'Erlang', mode: 'text/x-erlang' },
//     { name: 'Factor', mode: 'text/x-factor' },
//     { name: 'Forth', mode: 'text/x-forth' },
//     { name: 'Fortran', mode: 'text/x-fortran' },
//     { name: 'GO Lang', mode: 'text/x-go' },
//     { name: 'Groovy', mode: 'text/x-groovy' },
//     { name: 'Haskell', mode: 'text/x-haskell' },
//     { name: 'Haxe', mode: 'text/x-haxe' },
//     { name: 'Java', mode: 'text/x-java' },
//     { name: 'Lua', mode: 'text/x-lua' },
//     { name: 'Ocaml', mode: 'text/x-ocaml' },
//     { name: 'Octave', mode: 'text/x-octave' },
//     { name: 'Pascal', mode: 'text/x-pascal' },
//     { name: 'Perl', mode: 'text/x-perl' },
//     { name: 'PHP', mode: 'application/x-httpd-php' },
//     { name: 'Python 3', mode: 'text/x-python' },
//     { name: 'R Language', mode: 'text/x-rsrc' },
//     { name: 'Ruby', mode: 'text/x-ruby' },
//     { name: 'RUST', mode: 'text/x-rustsrc' },
//     { name: 'Scala', mode: 'text/x-scala' },
//     { name: 'Scheme', mode: 'text/x-scheme' },
//     { name: 'SmallTalk', mode: 'text/x-stsrc' },
//     { name: 'SQL', mode: 'text/x-sql' },
//     { name: 'Swift', mode: 'text/x-swift' },
//     { name: 'TCL', mode: 'text/x-tcl' },
//     { name: 'VB.Net', mode: 'text/x-vb' },
//     { name: 'VERILOG', mode: 'text/x-verilog' }
//   ];

const languages = [
    { name: 'c', mode: 'text/x-csrc' },
    { name: 'c_cpp', mode: 'text/x-c++src' },
    { name: 'csharp', mode: 'text/x-csharp' },
    { name: 'fortran', mode: 'text/x-fortran' },
    { name: 'golang', mode: 'text/x-go' },
    { name: 'java', mode: 'text/x-java' },
    { name: 'perl', mode: 'text/x-perl' },
    { name: 'php', mode: 'application/x-httpd-php' },
    { name: 'Python', mode: 'text/x-python' },
    { name: 'r', mode: 'text/x-rsrc' },
    { name: 'ruby', mode: 'text/x-ruby' },
    { name: 'swift', mode: 'text/x-swift' },
  ];
  
  export default languages;
  